
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/moneytransferdb
        username: firalammii
        password: f1r4lam311
        initialization-mode: always
##kmdf

    jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.show-sql : true
    jpa.hibernate.ddl-auto : update
    jpa.properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect


